#!/bin/zsh

# 获取目录参数，默认为当前终端的目录
directory=${1:-$(pwd)}

# 遍历指定目录下的所有.out文件
for file in "$directory"/*.out; do
    if [ -f "$file" ]; then
        # 提取文件名前缀数字
        prefix=$(basename "$file" | grep -o '^[0-9]*')
        # 查找相同前缀数字的.cpp文件
        cpp_file=$(find "$directory" -type f -name "${prefix}*.cpp" -print -quit)

        # 如果找到对应的.cpp文件，则移动.out文件到同目录下
        if [ -n "$cpp_file" ]; then
            mv "$file" "$(dirname "$cpp_file")"
            echo "Moved $file to $(dirname "$cpp_file")"
        else
            echo "No corresponding .cpp file found for $file"
        fi
    fi
done